# Generated by Django 4.1.3 on 2022-11-30 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_size_alter_productvaraiant_brand_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvaraiant',
            name='unique_prod_color_size_combo',
        ),
        migrations.AlterField(
            model_name='productvaraiant',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.brand'),
        ),
        migrations.AlterField(
            model_name='productvaraiant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.colour'),
        ),
        migrations.AlterField(
            model_name='productvaraiant',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.size'),
        ),
        migrations.AddConstraint(
            model_name='productvaraiant',
            constraint=models.UniqueConstraint(fields=('product', 'color', 'size', 'brand'), name='unique_prod_color_size_combo'),
        ),
    ]
