# Generated by Django 4.1.3 on 2022-12-01 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_description'),
        ('shop', '0003_remove_productvaraiant_unique_prod_color_size_combo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procat', to='category.category'),
        ),
    ]
