# Generated by Django 4.1.3 on 2022-12-02 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_productvaraiant_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvaraiant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color', to='shop.colour'),
        ),
    ]
